/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/friendship/request/{friendId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sends a friend request from the currently authenticated user to another user specified by their ID.
         * @description This endpoint allows the currently authenticated user to send a friend request to another user by providing the target user's ID as a path parameter. The request must include a valid authentication token to access this endpoint. If the friend request is successfully sent, the newly created friendship entity representing the pending friend request is returned.
         */
        post: operations["UserController_sendFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/friendship/{friendshipId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Accepts a pending friend request for the currently authenticated user.
         * @description This endpoint allows the currently authenticated user to accept a pending friend request by providing the friendship ID as a path parameter. The request must include a valid authentication token to access this endpoint. If the friend request is successfully accepted, the updated friendship entity representing the accepted friendship is returned.
         */
        patch: operations["UserController_acceptFriendRequest"];
        trace?: never;
    };
    "/user/me/friendship/{friendshipId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rejects a pending friend request for the currently authenticated user.
         * @description This endpoint allows the currently authenticated user to reject a pending friend request by providing the friendship ID as a path parameter. The request must include a valid authentication token to access this endpoint. If the friend request is successfully rejected, the updated friendship entity representing the rejected friendship is returned.
         */
        patch: operations["UserController_rejectFriendRequest"];
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user.
         * @description This endpoint allows clients to register a new user by providing an email and password. The password must be confirmed by including a matching password confirmation field. If the registration is successful, the newly created user entity is returned.
         */
        post: operations["UserController_registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the profile of the currently authenticated user.
         * @description This endpoint allows clients to fetch the profile information of the currently authenticated user. The user's identity is determined from the authentication token included in the request. If the user is successfully authenticated, their profile information is returned.
         */
        get: operations["UserController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Updates the profile of the currently authenticated user.
         * @description This endpoint allows clients to update the profile information of the currently authenticated user. The user's identity is determined from the authentication token included in the request. The request body should contain the new profile information (bio, display name, and MOTD). If the update is successful, the updated profile entity is returned.
         */
        patch: operations["UserController_updateMyProfile"];
        trace?: never;
    };
    "/user/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the profile of a user by their ID.
         * @description This endpoint allows clients to fetch the profile information of a user by providing their unique ID as a path parameter. The request must include a valid authentication token to access this endpoint. If the user with the specified ID exists and the requester is authenticated, the user's profile information is returned.
         */
        get: operations["UserController_getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handles user login by accepting login credentials and returning JWT tokens.
         * @description This endpoint accepts a POST request with the user's email and password, validates the credentials, and returns an access token, refresh token, and expiration time if the login is successful.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handles token refresh by accepting a refresh token and returning new JWT tokens.
         * @description This endpoint accepts a POST request with a refresh token, validates the token, and returns a new access token, new refresh token, and expiration time if the token is valid.
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Profile: {
            id: string;
            /** Format: date-time */
            updatedAt: string;
            displayName: string;
            bio?: string;
            motd?: string;
            /** @enum {string} */
            status: "default" | "suspended" | "banned";
            avatarUrl?: string;
            bannerUrl?: string;
            owner: components["schemas"]["User"];
        };
        ChatChannelMessage: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            channel: components["schemas"]["ChatChannel"];
            author: components["schemas"]["User"];
            content: string;
        };
        UserToChatChannel: {
            id: string;
            chatChannelId: string;
            userId: string;
            /** Format: date-time */
            lastReadAt: string;
            chatChannel: components["schemas"]["ChatChannel"];
            user: components["schemas"]["User"];
        };
        ChatChannel: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            server: components["schemas"]["Server"];
            messages: components["schemas"]["ChatChannelMessage"][];
            userStates: components["schemas"]["UserToChatChannel"][];
        };
        Server: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            name: string;
            description: string;
            motd: string;
            avatarUrl: string;
            bannerUrl: string;
            participants: components["schemas"]["UserToServer"][];
            chatChannels: components["schemas"]["ChatChannel"][];
        };
        UserToServer: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["User"];
            server: components["schemas"]["Server"];
        };
        ConversationMessage: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            conversation: components["schemas"]["Conversation"];
            author: components["schemas"]["User"];
        };
        Conversation: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            name: string;
            participants: components["schemas"]["UserToConversation"][];
            messages: components["schemas"]["ConversationMessage"][];
        };
        UserToConversation: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastReadAt: string;
            userId: string;
            conversationId: string;
            user: components["schemas"]["User"];
            conversation: components["schemas"]["Conversation"];
        };
        Friendship: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            requesterId: string;
            recipientId: string;
            requester: components["schemas"]["User"];
            recipient: components["schemas"]["User"];
        };
        User: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            email: string;
            passwordHash: string;
            profile: components["schemas"]["Profile"];
            servers: components["schemas"]["UserToServer"][];
            conversations: components["schemas"]["UserToConversation"][];
            chatChannelStates: components["schemas"]["UserToChatChannel"][];
            sentFriendships: components["schemas"]["Friendship"][];
            receivedFriendships: components["schemas"]["Friendship"][];
        };
        RegisterUserDto: {
            email: string;
            password: string;
            passwordConfirmation: string;
        };
        UpdateProfileDto: {
            /**
             * @description The user's biography or personal description. This field allows users to provide a brief introduction about themselves, their interests, or any other information they wish to share. It is typically displayed on the user's profile page and can be updated by the user at any time.
             * @example Im a bean enthusiast
             */
            bio: string;
            /**
             * @description The display name chosen by the user. This is the name that will be shown to other users on the platform and can be different from the user's email or username. The display name is often used to personalize the user's profile and can be updated by the user at any time.
             * @example BeanLover123
             */
            displayName: string;
            /**
             * @description The message of the day (MOTD) is a short message that users can set to share with others when they visit their profile. It can be used to convey a current mood, a quote, or any other brief message the user wants to display. The MOTD is typically shown prominently on the user's profile page and can be updated by the user at any time.
             * @example Living life one bean at a time!
             */
            motd: string;
        };
        LoginDto: {
            email: string;
            password: string;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            expiresIn: number;
        };
        RefreshDto: {
            refreshToken: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UserController_sendFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Friendship"];
                };
            };
            /** @description Bad Request - If the specified friend ID is invalid or if a friend request already exists between the users. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - If the user is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If no user exists with the specified friend ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_acceptFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendshipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Friendship"];
                };
            };
            /** @description Bad Request - If the specified friendship ID is invalid or if the friend request cannot be accepted. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - If the user is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If no friendship exists with the specified ID or if the friendship does not belong to the authenticated user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_rejectFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendshipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Friendship"];
                };
            };
            /** @description Bad Request - If the specified friendship ID is invalid or if the friend request cannot be rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - If the user is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If no friendship exists with the specified ID or if the friendship does not belong to the authenticated user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad Request - If the password and confirmation do not match, or if the email is already in use. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unauthorized - If the user is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If the user associated with the authentication token does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Bad Request - If the provided profile information is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized - If the user is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If the user associated with the authentication token does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unauthorized - If the requester is not authenticated or if the authentication token is invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found - If no user exists with the specified ID. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
}
