/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user.
         * @description This endpoint allows clients to register a new user by providing an email and password. The password must be confirmed by including a matching password confirmation field. If the registration is successful, the newly created user entity is returned.
         */
        post: operations["UserController_registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handles user login by accepting login credentials and returning JWT tokens.
         * @description This endpoint accepts a POST request with the user's email and password, validates the credentials, and returns an access token, refresh token, and expiration time if the login is successful.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handles token refresh by accepting a refresh token and returning new JWT tokens.
         * @description This endpoint accepts a POST request with a refresh token, validates the token, and returns a new access token, new refresh token, and expiration time if the token is valid.
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the profile of the currently authenticated user.
         * @description This endpoint retrieves the profile information of the user making the request. The user's ID is extracted from the request object, and the corresponding profile is fetched from the database. If the user or profile is not found, an appropriate error response is returned.
         *     @return The profile associated with the currently authenticated user.
         */
        get: operations["ProfileController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the profile of the currently authenticated user.
         * @description This endpoint allows the user to update their profile information, such as display name, bio, message of the day (MOTD), and handle. The user's ID is extracted from the request object, and the provided profile data is validated and saved to the database. If the user or profile is not found, or if the provided handle is already taken by another profile, an appropriate error response is returned.
         *     @return The updated profile after saving it to the database.
         */
        patch: operations["ProfileController_updateMyProfile"];
        trace?: never;
    };
    "/profile/handle/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check if a given handle already exists in the system.
         * @description This endpoint allows clients to check if a specific handle is already taken by another profile. The handle is provided as a query parameter, and the response indicates whether the handle exists or not. This can be useful for validating handle availability during profile creation or updates.
         *     @return An object containing the handle and a boolean indicating whether it exists.
         */
        get: operations["ProfileController_handleExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterUserDto: {
            email: string;
            password: string;
            passwordConfirmation: string;
        };
        ChatChannelMessage: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            channel: components["schemas"]["ChatChannel"];
            author: components["schemas"]["User"];
            content: string;
        };
        UserToChatChannel: {
            id: string;
            chatChannelId: string;
            userId: string;
            /** Format: date-time */
            lastReadAt: string;
            chatChannel: components["schemas"]["ChatChannel"];
            user: components["schemas"]["User"];
        };
        ChatChannel: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            server: components["schemas"]["Server"];
            messages: components["schemas"]["ChatChannelMessage"][];
            userStates: components["schemas"]["UserToChatChannel"][];
        };
        Server: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            name: string;
            description: string;
            motd: string;
            avatarUrl: string;
            bannerUrl: string;
            participants: components["schemas"]["UserToServer"][];
            chatChannels: components["schemas"]["ChatChannel"][];
        };
        UserToServer: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["User"];
            server: components["schemas"]["Server"];
        };
        ConversationMessage: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            conversation: components["schemas"]["Conversation"];
            author: components["schemas"]["User"];
        };
        Conversation: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            name: string;
            participants: components["schemas"]["UserToConversation"][];
            messages: components["schemas"]["ConversationMessage"][];
        };
        UserToConversation: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastReadAt: string;
            userId: string;
            conversationId: string;
            user: components["schemas"]["User"];
            conversation: components["schemas"]["Conversation"];
        };
        Friendship: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            requesterId: string;
            recipientId: string;
            requester: components["schemas"]["User"];
            recipient: components["schemas"]["User"];
        };
        User: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            email: string;
            passwordHash: string;
            profile: components["schemas"]["Profile"];
            servers: components["schemas"]["UserToServer"][];
            conversations: components["schemas"]["UserToConversation"][];
            chatChannelStates: components["schemas"]["UserToChatChannel"][];
            sentFriendships: components["schemas"]["Friendship"][];
            receivedFriendships: components["schemas"]["Friendship"][];
        };
        Profile: {
            id: string;
            /** Format: date-time */
            updatedAt: string;
            displayName: string;
            handle: string;
            bio?: string;
            motd?: string;
            /** @enum {string} */
            status: "default" | "suspended" | "banned";
            avatarUrl?: string;
            bannerUrl?: string;
            owner: components["schemas"]["User"];
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            expiresIn: number;
        };
        RegistrationResponseDto: {
            profile: components["schemas"]["Profile"];
            tokenPair: components["schemas"]["TokenPair"];
        };
        LoginDto: {
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        UpdateProfileDto: {
            /**
             * @description The user's biography or personal description. This field allows users to provide a brief introduction about themselves, their interests, or any other information they wish to share. It is typically displayed on the user's profile page and can be updated by the user at any time.
             * @example Im a bean enthusiast
             */
            bio: string;
            /**
             * @description The display name chosen by the user. This is the name that will be shown to other users on the platform and can be different from the user's email or username. The display name is often used to personalize the user's profile and can be updated by the user at any time.
             * @example BeanLover123
             */
            displayName: string;
            /**
             * @description The message of the day (MOTD) is a short message that users can set to share with others when they visit their profile. It can be used to convey a current mood, a quote, or any other brief message the user wants to display. The MOTD is typically shown prominently on the user's profile page and can be updated by the user at any time.
             * @example Living life one bean at a time!
             */
            motd: string;
            /**
             * @description The user's handle is a unique identifier that can be used to mention or refer to the user within the platform. It is often used in URLs, mentions, and other contexts where a unique identifier is needed. The handle is typically chosen by the user and must be unique across the platform. It can be updated by the user, but care should be taken to ensure that it remains unique.
             * @example beanlover123
             */
            handle: string;
        };
        HandleExistsResponseDto: {
            handle: string;
            exists: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UserController_registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponseDto"];
                };
            };
            /** @description Bad Request - If the password and confirmation do not match, or if the email is already in use. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    ProfileController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description if the user or profile is not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description if the provided handle is already taken by another profile. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description if the user or profile is not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_handleExists: {
        parameters: {
            query: {
                handle: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandleExistsResponseDto"];
                };
            };
        };
    };
}
